## Misc

In [19]:
f = open('../2020-Summer/data1.txt', 'wb')
for i in range(54):
    f.write((65).to_bytes(1,'big'))
f.close()

In [22]:
f = open('../2020-Summer/data2.bin', 'wb')
f.write((41).to_bytes(1,'big'))
f.write((42).to_bytes(1,'big'))
f.write((43).to_bytes(1,'big'))
f.write((44).to_bytes(1,'big'))
f.write((45).to_bytes(1,'big'))
f.write((46).to_bytes(1,'big'))
f.write((47).to_bytes(1,'big'))
f.write((0).to_bytes(1,'big'))
f.write((6).to_bytes(1,'big'))
f.write((5).to_bytes(1,'big'))
f.write((0).to_bytes(1,'big'))
f.write((0).to_bytes(1,'big'))
f.write((0).to_bytes(1,'big'))
f.write((0).to_bytes(1,'big'))
f.write((8).to_bytes(1,'big'))
f.write((4).to_bytes(1,'big'))
f.write((48).to_bytes(1,'big'))
f.close()

In [28]:
dct = 'plmoknij buhvygctfxrdz.esawq'
txt = "i have no idea what is your problem so please help me"

with open('../2020-Summer/data4.txt', 'w') as f:
    for c in txt:
        if c.isalpha():
            f.write(dct[ord(c.lower())-ord('a')])
        elif c == ' ':
            f.write(dct[-2])
        elif c == '.': # is a period
            f.write(dct[-1:])

In [3]:
s = "abcd"
print(s[0:2])

ab


In [34]:
import math

p2 = math.pow(2,26)
sum_p = 12345 * (1103515245^2-1) / (1103515245 - 1)
print(p2)
print(1103515245 + 12345)
print((1103515245 + 12345) % math.pow(2,26))
print((1103515245*29785766.0 + 12345)% math.pow(2,26))
print(sum_p == 12345)
print((1103515245*29785766.0 + sum_p)% p2)

67108864.0
1103527590
29785766.0
41857256.0
True
41857256.0


In [13]:
a = "(abs)"
print(a[1:-1])

print(min(1, 2, 3))
if min(1, 2, 3) > 3:
    print("NO")

abs
1


In [5]:
import math

side = 10
height_1 = math.sqrt(3)*side /2
height_2 = math.sqrt(math.pow(side,2) - math.pow(side/2,2))

print(height_1, height_2)
print(side*height_1/2)

8.660254037844386 8.660254037844387
43.301270189221924


In [10]:
a = '12'
b = '0' * 5
n = a + b
print(n)

1200000


In [11]:
e1 = 9
e2 = 9

a_r = int(e1) * int(e2)
zeros = '0' * (10)
a_r_s = str(a_r) + zeros

b_r = math.floor(int(e1)*int(e2)*math.pow(10,10))
b_r_s = str(b_r)

print(a_r_s, b_r_s)

810000000000 810000000000


## Numpy

In [7]:
import numpy as np

In [11]:
# a = np.random.randint(low=0,high=30,size=(3,2))
a = np.array([[0,1], [1,0], [1,1]])
print(a, np.size(a, axis=0))

x_axis = a[:,0]
y_axis = a[:,1]
multi_xy = x_axis * y_axis
x_sqr = x_axis ** 2

print( np.sum(multi_xy), np.sum(x_axis) * np.sum(y_axis), np.sum(x_sqr), np.sum(x_axis)**2)

[[0 1]
 [1 0]
 [1 1]] 3
1 4 2 4


In [19]:
b = np.array([[1,10], [2,11], [5,16]])
p_1 = b[(b[:,0] < 4)]
print(p_1)

[[ 5 16]]


In [8]:
a = np.float32(0)
print(a)

0.0


In [17]:
from matplotlib import image

img = image.imread('image2.bmp')
print(img.shape, len(img), len(img[0]), len(img[0][0]))
print(img[0,0])
with open('image2.txt', 'w') as f:
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            for k in range(min(img.shape[2],3)):
                f.write(f"{int(img[i,j,k])} ")


(1025, 1600, 4) 1025 1600 4
[150 150 150 255]
